mutation UpdateAcClassificationType(
  $id: UUID!
  $lastchange: DateTime!
  $name: String
  $name_en: String
) {
  programClassificationTypeUpdate(
    classificationType: {
      id: $id
      lastchange: $lastchange
      name: $name
      nameEn: $name_en
    }
  ) {
    __typename
    ...Error
    ...AcClassificationType
  }
}

fragment Error on AcClassificationTypeGQLModelUpdateError {
  msg
  input
  failed
  Entity {
    lastchange
  }
}

fragment AcClassificationType on AcClassificationTypeGQLModel {
  id
  lastchange
  name
  nameEn
}
