query AcProgramStudentPage($skip: Int, $limit: Int) {
  result: acProgramStudentPage(skip: $skip, limit: $limit) {
    id
    lastchange
    student {
      id
    }
    messages {
      id
    }
    state {
      id
    }
  }
}
