mutation DeleteAcClassification($id: UUID!, $lastchange: DateTime!) {
  programClassificationDelete(
    classification: {
      id: $id
      lastchange: $lastchange
    }
  ) {
    __typename
    ...Error
  }
}

fragment Error on AcClassificationGQLModelDeleteError {
  msg
  input
  failed
  Entity {
    id
    lastchange
  }
}

