query ($id: UUID!) {
    result: acClassificationById(id: $id) {
        __typename
        ...AcClassification
    }
}

fragment AcClassification on AcClassificationGQLModel {
    id
    lastchange
    date
    order
    student {
        id
    }
    semester {
        id
    }
    level {
        id
    }
}

