mutation UpdateAcClassification(
  $id: UUID!
  $lastchange: DateTime!
  $classificationlevel_id: UUID
  $order: Int
  $date: DateTime
) {
  programClassificationUpdate(
    classification: {
      id: $id
      lastchange: $lastchange
      classificationlevelId: $classificationlevel_id
      order: $order
      date: $date
    }
  ) {
    __typename
    ...Error
    ...AcClassification
  }
}

fragment Error on AcClassificationGQLModelUpdateError {
  msg
  input
  failed
  Entity {
    lastchange
  }
}

fragment AcClassification on AcClassificationGQLModel {
  id
  lastchange
  level{
    id
  }
  student{
    id
  }
  order
  date
  semester{
    id
  }
}
