query AcLessonTypeById($id: UUID!) {
    result: acLessonTypeById(id: $id) {
        __typename
        ...AcLessonType
    }
}

fragment AcLessonType on AcLessonTypeGQLModel {
    id
    name
    nameEn
    lastchange
}
