query {
    result: acProgramTypePage {
        __typename
        ...AcProgramType
    }
}

fragment AcProgramType on AcProgramTypeGQLModel {
    id
    name
    nameEn
    level {
        id
    }
    form {
        id
    }
    language {
        id
    }
    title {
        id
    }
}
