query AcSemesterPage($skip: Int, $limit: Int) {
  result: acSemesterPage(skip: $skip, limit: $limit) {
    id
    lastchange
    order
    subject {
      id
    }
    classifications {
      id
    }
    classificationType {
      id
    }
    topics {
      id
    }
  }
}
