mutation AddAcTopic(
  $id: UUID
  $name: String!
  $name_en: String
  $order: Int  
  $semester_id: UUID!
) {
  programTopicInsert(
    topic: {
      id: $id
      name: $name
      nameEn: $name_en
      order: $order
      semesterId: $semester_id
    }
  ) {
    __typename
    ...Error
    ...AcTopic
  }
}

fragment Error on InsertError {
  __typename
  msg
  input
  failed
}

fragment AcTopic on AcTopicGQLModel {
  __typename
  id
  lastchange
  name
  nameEn
  order
  semester{
    id
  }
}
