mutation UpdateAcTopic(
  $id: UUID!
  $lastchange: DateTime!
  $name: String
) {
  programTopicUpdate(
    topic: {
      id: $id
      lastchange: $lastchange
      name: $name
    }
  ) {
    __typename
    ...Error
    ...AcTopic
  }
}

fragment Error on AcTopicGQLModelUpdateError {
  msg
  input
  failed
  Entity {
    lastchange
  }
}

fragment AcTopic on AcTopicGQLModel {
  id
  lastchange
  name
}
