query {
    result: acClassificationLevelPage {
        __typename
        ...AcClassificationLevel
    }
}

fragment AcClassificationLevel on AcClassificationLevelGQLModel {
    id
    name
    nameEn
}
