query AcClassificationLevelPage($skip: Int, $limit: Int) {
    result: acClassificationLevelPage(skip: $skip, limit: $limit) {
        __typename
        ...AcClassificationLevel
    }
}

fragment AcClassificationLevel on AcClassificationLevelGQLModel {
    id
    name
    nameEn
}
