mutation AddAcSemester(
  $id: UUID
  $subject_id: UUID!
  $order: Int!
  $classificationtype_id: UUID!
  $valid: Boolean!
) {
  programSemesterInsert(
    semester: {
      id: $id
      subjectId: $subject_id
      order: $order
      classificationtypeId: $classificationtype_id
      valid: $valid
    }
  ) {
    __typename
    ...Error
    ...AcSemester
  }
}

fragment Error on InsertError {
  __typename
  msg
  input
  failed
}

fragment AcSemester on AcSemesterGQLModel {
  __typename
  id
  lastchange
  subject{
    id
  }
  order
  classificationType{
    id
  }
}
