mutation UpdateAcSemester(
  $id: UUID!
  $lastchange: DateTime!
  $order: Int
  $classificationtype_id: UUID
) {
  programSemesterUpdate(
    semester: {
      id: $id
      lastchange: $lastchange
      order: $order
      classificationtypeId: $classificationtype_id
    }
  ) {
    __typename
    ...Error
    ...AcSemester
  }
}

fragment Error on AcSemesterGQLModelUpdateError {
  msg
  input
  failed
  Entity {
    lastchange
  }
}

fragment AcSemester on AcSemesterGQLModel {
  id
  lastchange
  order
  classificationType{
    id
  }
}
