mutation AddAcProgramStudent(
  $id: UUID
  $program_id: UUID!
  $state_id: UUID!
  $student_id: UUID!
  $semester: Int
) {
  programStudentInsert(
    student: {
      id: $id
      programId: $program_id
      stateId: $state_id
      studentId: $student_id
      semester: $semester
    }
  ) {
    __typename
    ...Error
    ...AcProgramStudent
  }
}

fragment Error on InsertError {
  __typename
  msg
  input
  failed
}

fragment AcProgramStudent on AcProgramStudentGQLModel {
  __typename
  id
  lastchange
  program{
    id
  }
  state{
    id
  }
  student{
    id
  }
  semester
}
