mutation DeleteAcProgramStudent($id: UUID!, $lastchange: DateTime!) {
  programStudentDelete(
    student: {
      id: $id
      lastchange: $lastchange
    }
  ) {
    __typename
    ...Error
  }
}

fragment Error on AcProgramStudentGQLModelDeleteError {
  msg
  input
  failed
  Entity {
    id
    lastchange
  }
}
