query {
    result: acProgramStudentPage {
        __typename
        ...AcProgramStudent
    }
}

fragment AcProgramStudent on AcProgramStudentGQLModel {
    id
    lastchange
    student {
        id
    }
    messages {
        id
    }
    state {
        id
    }
}
