mutation UpdateAcProgramStudent(
  $id: UUID!
  $state_id: UUID!
  $semester: Int
  $lastchange: DateTime!
  $name: String!
) {
  programStudentUpdate(
    student: {
      id: $id
      lastchange: $lastchange
      stateId: $state_id
      semester: $semester
      name: $name
    }
  ) {
    __typename
    ...Error
    ...AcProgramStudent
  }
}

fragment Error on AcProgramStudentGQLModelUpdateError {
  msg
  input
  failed
  Entity {
    lastchange
  }
}

fragment AcProgramStudent on AcProgramStudentGQLModel {
  id
  lastchange
  state{
    id
  }
  semester
}
