mutation AddAcProgramLevel(
  $id: UUID
  $name: String!
  $name_en: String
) {
  programLevelTypeInsert(
    levelType: {
      id: $id
      name: $name
      nameEn: $name_en
    }
  ) {
    __typename
    ...Error
    ...AcProgramLevel
  }
}

fragment Error on InsertError {
  __typename
  msg
  input
  failed
}

fragment AcProgramLevel on AcProgramLevelTypeGQLModel {
  __typename
  id
  name
  nameEn
  lastchange
}
