mutation DeleteAcProgramLevel($id: UUID!, $lastchange: DateTime!) {
  programLevelTypeDelete(
    levelType: {
      id: $id
      lastchange: $lastchange
    }
  ) {
    __typename
    ...Error
  }
}

fragment Error on AcProgramLevelTypeGQLModelDeleteError {
  msg
  input
  failed
  Entity {
    id
    lastchange
  }
}
