mutation UpdateAcProgramLevel(
  $id: UUID!
  $lastchange: DateTime!
  $name: String
  $name_en: String

) {
  programLevelTypeUpdate(
    levelType: {
      id: $id
      lastchange: $lastchange
      name: $name
      nameEn: $name_en
    }
  ) {
    __typename
    ...Error
    ...AcProgramLevel
  }
}

fragment Error on AcProgramLevelTypeGQLModelUpdateError {
  msg
  input
  failed
  Entity {
    lastchange
  }
}

fragment AcProgramLevel on AcProgramLevelTypeGQLModel {
  id
  lastchange
  name
  nameEn
}
