query AcProgramStudentStatePage($skip: Int, $limit: Int) {
    result: acProgramStudentStatePage(skip: $skip, limit: $limit) {
        __typename
        ...AcProgramStudentState
    }
}

fragment AcProgramStudentState on AcProgramStudentStateGQLModel {
    id
    name
    nameEn
}

