mutation AddAcLesson(
  $id: UUID
  $count: Int!
  $type_id: UUID!
  $topic_id: UUID!
) {
  programLessonInsert(
    lesson: {
      id: $id
      count: $count
      typeId: $type_id
      topicId: $topic_id
    }
  ) {
    __typename
    ...Error
    ...AcLesson
  }
}

fragment Error on InsertError {
  __typename
  msg
  input
  failed
}

fragment AcLesson on AcLessonGQLModel {
  __typename
  id
  lastchange
  count
  type{
    id
  }
  topic{
    id
  }
}
