mutation UpdateAcLesson(
  $id: UUID!
  $lastchange: DateTime!
  $count: Int
  $type_id: UUID
) {
  programLessonUpdate(
    lesson: {
      id: $id
      lastchange: $lastchange
      count: $count
      typeId: $type_id
    }
  ) {
    __typename
    ...Error
    ...AcLesson
  }
}

fragment Error on AcLessonGQLModelUpdateError {
  msg
  input
  failed
  Entity {
    lastchange
  }
}

fragment AcLesson on AcLessonGQLModel {
  id
  count
  lastchange
  type{
    id
  }
  topic{
    id
  }
}
