query AcProgramTitleTypePage($skip: Int, $limit: Int) {
    result: acProgramTitleTypePage(skip: $skip, limit: $limit) {
        __typename
        ...AcProgramTitleType
    }
}

fragment AcProgramTitleType on AcProgramTitleTypeGQLModel {
    id
    lastchange
    name
    nameEn
}
