query AcProgramPage($skip: Int, $limit: Int) {
  result: acProgramPage(skip: $skip, limit: $limit) {
    id
    name
    nameEn
    type {
      id
    }
    subjects {
      id
    }
    students {
      id
    }
    grantsGroup {
      id
    }
    licencedGroup {
      id
    }
    createdby {
      id
    }
    changedby {
      id
    }
    rbacobject {
      id
    }
  }
}
