mutation DeleteAcProgramForm($id: UUID!, $lastchange: DateTime!) {
  programFormTypeDelete(
    formType: {
      id: $id
      lastchange: $lastchange
    }
  ) {
    __typename
    ...Error
  }
}

fragment Error on AcProgramFormTypeGQLModelDeleteError {
  msg
  input
  failed
  Entity {
    id
    lastchange
  }
}
