query {
    result: acProgramFormTypePage {
        __typename
        ...AcProgramFormType
    }
}

fragment AcProgramFormType on AcProgramFormTypeGQLModel {
    id
    lastchange
    name
    nameEn
}
