mutation UpdateAcProgramStudentState(
  $id: UUID!
  $lastchange: DateTime!
  $name: String
  $name_en: String
) {
  acProgramStudentStateUpdate(
    programStudentState: {
      id: $id
      lastchange: $lastchange
      name: $name
      nameEn: $name_en
    }
  ) {
    __typename
    ...Error
    ...AcProgramStudentState
  }
}

fragment Error on AcProgramStudentStateUpdateError {
  msg
  input
  failed
  Entity {
    lastchange
  }
}

fragment AcProgramStudentState on AcProgramStudentStateGQLModel {
  id
  lastchange
  name
  nameEn
}
