mutation AddAcProgramStudentMessage(
  $id: UUID
  $name: String!
  $name_en: String!
) {
  acProgramStudentMessageInsert(
    programStudentMessage: {
      id: $id
      name: $name
      nameEn: $name_en
    }
  ) {
    __typename
    ...Error
    ...AcProgramStudentMessage
  }
}

fragment Error on InsertError {
  __typename
  msg
  input
  failed
}

fragment AcProgramStudentMessage on AcProgramStudentMessageGQLModel {
  __typename
  id
  name
  nameEn
  lastchange
}
