mutation AddAcProgramStudentMessage(
  $id: UUID
  $name: String!
  $date: DateTime!
  $description: String
  $program_id: UUID!
  $student_id: UUID!
) {
  programMessageInsert(
    message: {
      id: $id
      name: $name
      date: $date
      description: $description
      programId: $program_id
      studentId: $student_id
    }
  ) {
    __typename
    ...Error
    ...AcProgramStudentMessage
  }
}

fragment Error on InsertError {
  __typename
  msg
  input
  failed
}

fragment AcProgramStudentMessage on AcProgramMessageGQLModel {
  __typename
  id
  name
  lastchange
  date
  description
  program{
    id
  }
  student{
    id
  }
}
