mutation DeleteAcProgramStudentMessage($id: UUID!, $lastchange: DateTime!) {
  programMessageDelete(
    message: {
      id: $id
      lastchange: $lastchange
    }
  ) {
    __typename
    ...Error
  }
}

fragment Error on AcProgramMessageGQLModelDeleteError {
  msg
  input
  failed
  Entity {
    id
    lastchange
  }
}
