query AcProgramMessageById($id: UUID!) {
    result: acProgramMessageById(id: $id) {
        __typename
        ...AcProgramMessage
    }
}

fragment AcProgramMessage on AcProgramMessageGQLModel {
    id
    name
    description
    date
    lastchange
    program {
        id
    }
}