mutation UpdateAcProgramStudentMessage(
  $id: UUID!
  $lastchange: DateTime!
  $name: String
  $date: DateTime!
) {
  programMessageUpdate(
    message: {
      id: $id
      lastchange: $lastchange
      name: $name
      date: $date
    }
  ) {
    __typename
    ...Error
    ...AcProgramStudentMessage
  }
}

fragment Error on AcProgramMessageGQLModelUpdateError {
  msg
  input
  failed
  Entity {
    lastchange
  }
}

fragment AcProgramStudentMessage on AcProgramMessageGQLModel {
  id
  lastchange
  name
  date
}
