mutation AddAcSubject(
  $id: UUID
  $name: String!
  $name_en: String
  $program_id: UUID!
  $group_id: UUID!
) {
  programSubjectInsert(
    subject: {
      id: $id
      name: $name
      nameEn: $name_en
      programId: $program_id
      groupId: $group_id
    }
  ) {
    __typename
    ...Error
    ...AcSubject
  }
}

fragment Error on InsertError {
  __typename
  msg
  input
  failed
}

fragment AcSubject on AcSubjectGQLModel {
  __typename
  id
  lastchange
  name
  nameEn
}
