query AcProgramMessagePage($skip: Int, $limit: Int) {
    result: acProgramMessagePage(skip: $skip, limit: $limit) {
        __typename
        ...AcProgramMessage
    }
}

fragment AcProgramMessage on AcProgramMessageGQLModel {
    id
    name
    description
    date
    student {
        id
    }
    program {
        id
    }
}
