query {
    result: acClassificationTypePage {
        __typename
        ...AcClassificationType
    }
}

fragment AcClassificationType on AcClassificationTypeGQLModel {
    id
    name
    nameEn
}
