query {
    result: acLessonPage {
        __typename
        ...AcLesson
    }
}

fragment AcLesson on AcLessonGQLModel {
    id
    lastchange
    count
    topic {
        id
    }
    type {
        id
    }
}
