mutation AddAcProgramLanguage($id: UUID, $name: String!, $name_en: String) {
  programLanguageTypeInsert(
    languageType: {
      id: $id
      name: $name
      nameEn: $name_en
    }
  ) {
    __typename
    ...Error
    ...AcProgramLanguage
  }
}

fragment Error on InsertError {
  __typename
  msg
  input
  failed
}

fragment AcProgramLanguage on AcProgramLanguageTypeGQLModel {
  __typename
  id
  name
  nameEn
  lastchange
}
