mutation DeleteAcProgramLanguage($id: UUID!, $lastchange: DateTime!) {
  programLanguageTypeDelete(
    languageType: {
      id: $id
      lastchange: $lastchange
    }
  ) {
    __typename
    ...Error
  }
}

fragment Error on AcProgramLanguageTypeGQLModelDeleteError {
  msg
  input
  failed
  Entity {
    id
    lastchange
  }
}
