mutation UpdateAcProgramLanguage(
  $id: UUID!
  $lastchange: DateTime!
  $name: String
  $name_en: String
) {
  programLanguageTypeUpdate(
    languageType: {
      id: $id
      lastchange: $lastchange
      name: $name
      nameEn: $name_en
    }
  ) {
    __typename
    ...Error
    ...AcProgramLanguage
  }
}

fragment Error on AcProgramLanguageTypeGQLModelUpdateError {
  msg
  input
  failed
  Entity {
    lastchange
  }
}

fragment AcProgramLanguage on AcProgramLanguageTypeGQLModel {
  id
  lastchange
  name
  nameEn
}
