query AcSubjectPage($skip: Int, $limit: Int) {
  result: acSubjectPage(skip: $skip, limit: $limit) {
    id
    lastchange
    name
    nameEn
    program {
      id
    }
    semesters {
      id
    }
    grants {
      id
    }
  }
}
