query AcSubjectById($id: UUID!) {
  result: acSubjectById(id: $id) {
    id
    lastchange
    name
    nameEn
    program {
      id
    }
    semesters {
      id
    }
    grants {
      id
    }
  }
}
