query AcProgramFormTypePage($skip: Int, $limit: Int) {
    result: acProgramFormTypePage(skip: $skip, limit: $limit) {
        __typename
        ...AcProgramFormType
    }
}

fragment AcProgramFormType on AcProgramFormTypeGQLModel {
    id
    lastchange
    name
    nameEn
}
