mutation AddAcProgram(
  $id: UUID
  $name: String!
  $type_id: UUID!
  $group_id: UUID!
  $licenced_group_id: UUID!
) {
  programInsert(
    program: {
      id: $id
      name: $name
      typeId: $type_id
      groupId: $group_id
      licencedGroupId: $licenced_group_id
    }
  ) {
    __typename
    ...Error
    ...AcProgram
  }
}

fragment Error on InsertError {
  __typename
  msg
  input
  failed
}

fragment AcProgram on AcProgramGQLModel {
  __typename
  id
  created
  lastchange
  name
  type{
    id
  }
  licencedGroup{
    id
  }
}
