query AcProgramById($id: UUID!) {
    result: acProgramById(id: $id) {
        __typename
        ...AcProgram
    }
}

fragment AcProgram on AcProgramGQLModel {
    id
    name
    nameEn
    lastchange
    type {
        id
    }
    subjects {
        id
    }
    students {
        id
    }
    grantsGroup {
        id
    }
    licencedGroup {
        id
    }
    createdby {
        id
    }
    changedby {
        id
    }
    rbacobject {
        id
    }
}
