mutation UpdateAcProgram(
  $id: UUID!
  $lastchange: DateTime!
  $name: String
  $type_id: UUID
) {
  programUpdate(
    program: {
      id: $id
      lastchange: $lastchange
      name: $name
      typeId: $type_id
    }
  ) {
    __typename
    ...Error
    ...AcProgram
  }
}

fragment Error on AcProgramGQLModelUpdateError {
  msg
  input
  failed
  Entity {
    lastchange
  }
}

fragment AcProgram on AcProgramGQLModel {
  id
  lastchange
  name
  type{
    id
  }
}
