mutation AddAcProgramTitle(
  $id: UUID
  $name: String!
  $name_en: String!
) {
  acProgramTitleInsert(
    programTitle: {
      id: $id
      name: $name
      nameEn: $name_en
    }
  ) {
    __typename
    ...Error
    ...AcProgramTitle
  }
}

fragment Error on InsertError {
  __typename
  msg
  input
  failed
}

fragment AcProgramTitle on AcProgramTitleGQLModel {
  __typename
  id
  name
  nameEn
  lastchange
}
