mutation DeleteAcProgramTitle($id: UUID!, $lastchange: DateTime!) {
  programTitleTypeDelete(
    titleType: {
      id: $id
      lastchange: $lastchange
    }
  ) {
    __typename
    ...Error
  }
}

fragment Error on AcProgramTitleTypeGQLModelDeleteError {
  msg
  input
  failed
  Entity {
    id
    lastchange
  }
}
