mutation UpdateAcProgramTitle(
  $id: UUID!
  $lastchange: DateTime!
  $name: String
  $name_en: String
) {
  acProgramTitleUpdate(
    programTitle: {
      id: $id
      lastchange: $lastchange
      name: $name
      nameEn: $name_en
    }
  ) {
    __typename
    ...Error
    ...AcProgramTitle
  }
}

fragment Error on AcProgramTitleUpdateError {
  msg
  input
  failed
  Entity {
    lastchange
  }
}

fragment AcProgramTitle on AcProgramTitleGQLModel {
  id
  lastchange
  name
  nameEn
}
