query ($skip: Int, $limit: Int) {
    result: acClassificationPage(skip: $skip, limit: $limit) {
        id
        lastchange
        date
        order
        student {
            id
        }
        semester {
            id
        }
        level {
            id
        }
    }
}
